server:
  port: 9006
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trabalho_lp3?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password:
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect